#!/bin/bash

# Prevent containers from exhausting the process table, killing the node. (Fork bomb.)
mkdir --parents /etc/systemd/system/docker.service.d
cat <<MARK > /etc/systemd/system/docker.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --default-ulimit nproc=5000:10000 --default-ulimit nofile=65600:65600
MARK

# Make sure kubelet gets restarted on exit.
mkdir --parents /etc/systemd/system/kubelet.service.d
cat <<MARK > /etc/systemd/system/kubelet.service.d/override.conf
[Service]
Restart=always
MARK

systemctl daemon-reload
systemctl restart docker
