{{- if .Values.albIngress.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "bootstrap.labels" . | indent 4 }}
  name: {{ .Values.albIngress.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.albIngress.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}