{{- $group := .Values.calico.crdGroup -}}
{{- if .Values.calico.enabled }}
{{- range .Values.calico.customResources }}
---
apiVersion: apiextensions.k8s.io/v1beta1
description: {{ .desc }}
kind: CustomResourceDefinition
metadata:
  labels:
{{ include "bootstrap.labels" $ | indent 4 }}
  name: {{ .plural }}.{{ $group }}
spec:
  scope: {{ .scope }}
  group: {{ $group }}
  version: {{ .version }}
  names:
    kind: {{ .kind }} 
    plural: {{ .plural }}
    singular: {{ .name }}
{{- end }}
{{- end }}