{{- $name := .Values.calico.name -}}
{{- if .Values.calico.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "bootstrap.labels" . | indent 4 }}
  name: {{ $name }}-typha-cpha
{{- end }}