{{- $name := .Values.calico.name -}}
{{- if .Values.calico.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{ include "bootstrap.labels" . | indent 4 }}
  name: {{ $name }}-typha-cpha
rules:
  - apiGroups: [""]
    resources:
    - configmaps
    verbs:
    - get
  - apiGroups: ["extensions"]
    resources:
    - deployments/scale
    verbs:
    - get
    - update
{{- end }}