{{- $name := .Values.calico.name -}}
{{- if .Values.calico.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "bootstrap.labels" . | indent 4 }}
  name: {{ $name }}-typha-horizontal-autoscaler
data:
  ladder: |-
    {
      "coresToReplicas": [],
      "nodesToReplicas":
      [
        [1, 1],
        [10, 2],
        [100, 3],
        [250, 4],
        [500, 5],
        [1000, 6],
        [1500, 7],
        [2000, 8]
      ]
    }
{{- end }}