{{- $name := .Values.calico.name -}}
{{- if .Values.calico.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
{{- if .Values.calico.typhaHpa.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.calico.typhaHpa.deploymentAnnotations | indent 4 }}
{{- end }}
  name: {{ $name }}-typha-horizontal-autoscaler
  labels:
    component: {{ $name }}-typha-autoscaler
{{ include "bootstrap.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: {{ $name }}-typha-autoscaler
  {{- if .Values.calico.typhaHpa.updateStrategy }}
  updateStrategy:
{{ toYaml .Values.calico.typhaHpa.updateStrategy | trim | indent 4 }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.calico.typhaHpa.podAnnotations }}
      annotations:
{{ toYaml .Values.calico.typhaHpa.podAnnotations | trim | indent 8 }}
      {{- end }}
      labels:
        component: {{ $name }}-typha-autoscaler
    spec:
      containers:
        - name: {{ $name }}-autoscaler
          image: {{ .Values.calico.typhaHpa.image.repository }}:{{ .Values.calico.typhaHpa.image.tag }}
          imagePullPolicy: "{{ .Values.calico.typhaHpa.image.pullPolicy }}"
          command:
            - /cluster-proportional-autoscaler
            - --namespace={{ .Release.Namespace }}
            - --configmap={{ $name }}-typha-horizontal-autoscaler
            - --target=deployment/{{ $name }}-typha
          {{- range $key, $value := .Values.calico.typhaHpa.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          {{- if .Values.calico.typhaHpa.resources }}
          resources:
{{ include "bootstrap.resources" . | trim | indent 12 }}
          {{- end }}
      serviceAccountName: {{ $name }}-typha-cpha
{{- end -}}
