{{- $name := .Values.calico.name -}}
{{- if .Values.calico.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
{{ include "bootstrap.labels" . | indent 4 }}
  name: {{ $name }}-typha-cpha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.calico.name }}-typha-cpha
subjects:
- kind: ServiceAccount
  name: {{ .Values.calico.name }}-typha-cpha
  namespace: {{ .Release.Namespace }}
{{- end }}