{{- $name := .Values.calico.name -}}
{{- if .Values.calico.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.calico.service.annotations }}
  annotations:
{{ toYaml .Values.calico.service.annotations | indent 4 }}
{{- end }}
  labels:
    component: {{ $name }}-typha
{{ include "bootstrap.labels" . | indent 4 }}
  name: {{ $name }}-typha
spec:
  ports:
    - port: {{ .Values.calico.typha.port }}
      protocol: TCP
      targetPort: {{ $name }}-typha
      name: {{ $name }}-typha
  selector:
    component: {{ $name }}-typha
{{- end }}
