{{- if .Values.externalDns.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "bootstrap.labels" . | indent 4 }}
  name: {{ .Values.externalDns.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.externalDns.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.externalDns.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}