apiVersion: v1
kind: LimitRange
metadata:
  name: default-limitrange
spec:
  limits:
  - default:
      memory: {{ .Values.resourceLimits.memory }}
      cpu: {{ .Values.resourceLimits.cpu }}
    defaultRequest:
      memory: {{ .Values.resourceLimits.memory }}
      cpu: {{ .Values.resourceLimits.cpu }}
    type: Container
